import React from "react";
import { ReportsIcon } from "@/components/Icons";

export default function ReportsPage() {
  return (
    <div className="space-y-6">
      <div className="pb-6 border-b border-mist/10">
        <h1 className="font-display text-3xl text-bone tracking-tight">
          Impact Reports
        </h1>
        <p className="font-sans text-mist text-sm mt-1">
          Donor-ready narrative reports and Cloudinary dynamic collages.
        </p>
      </div>

      <div className="p-12 rounded-2xl bg-ink-soft border border-dashed border-mist/20 text-center flex flex-col items-center justify-center">
        <div className="w-12 h-12 rounded-xl bg-ink border border-mist/20 flex items-center justify-center text-moss-bright mb-4">
          <ReportsIcon size={24} />
        </div>
        <h3 className="font-display text-lg text-bone mb-1">
          Impact Story Generator
        </h3>
        <p className="font-sans text-mist text-xs max-w-sm mb-4">
          One-click impact reporting generated by Gemini narrative synthesis and Cloudinary montages.
        </p>
      </div>
    </div>
  );
}
